### PR TITLE
feat: Turn on  feature toggles on prod (FPLA-2010)

### PR DESCRIPTION
**Pull request by tomaszpowroznik**
https://tools.hmcts.net/jira/browse/FPLA-2010

includes:

https://tools.hmcts.net/jira/browse/FPLA-1130
https://tools.hmcts.net/jira/browse/FPLA-1990
https://tools.hmcts.net/jira/browse/FPLA-1915
https://tools.hmcts.net/jira/browse/FPLA-1938

### CODE REVIEW

**Comment by Jamesnelson117** [comment]
We're turning on view application tab right? You are missing toggling on the hide of various tabs. see ccd-defintion/CaseTypeTab/2_Hearings/2_Hearings-nonprod.json

**Comment by lewisbirks** [comment]
> We're turning on view application tab right? You are missing toggling on the hide of various tabs. See `ccd-defintion/CaseTypeTab/2_Hearings/2_Hearings-nonprod.json`

@Jamesnelson117 note that for the hearing stuff it seems to be on the third tab and this conflicts with the draft orders tab, I believe that all that will happen is that the 2 tabs will appear one after the other based on my understanding of CCD but do we want to fix that in a separate PR?

**Comment by tomaszpowroznik** [comment]
> > We're turning on view application tab right? You are missing toggling on the hide of various tabs. See `ccd-defintion/CaseTypeTab/2_Hearings/2_Hearings-nonprod.json`
> 
> @Jamesnelson117 note that for the hearing stuff it seems to be on the third tab and this conflicts with the draft orders tab, I believe that all that will happen is that the 2 tabs will appear one after the other based on my understanding of CCD but do we want to fix that in a separate PR?

resolved

**Comment by tomaszpowroznik** [comment]
> We're turning on view application tab right? You are missing toggling on the hide of various tabs. See `ccd-defintion/CaseTypeTab/2_Hearings/2_Hearings-nonprod.json`

thanks, done

**Pull request merged**
