### PR TITLE
DFPL-969: Remove already approved draft order

### PR DESCRIPTION
**Pull request by DanCatchpole**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DFPL-969

### Change description ###
 - Adds a migration to remove a draft order that has already been approved
 - Adds method to MigrateCaseService to remove a hearingOrdersBundlesDraft

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by AlistairEdwinOsborne — APPROVED** [review]
brand new service? looks all good though!

**Comment by DanCatchpole** [comment]
> brand new service? looks all good though!
(weird can't reply to it directly)

Yeah, think it would be good if we moved all of the non 'runXYZ' functions into a service so we can keep them around + have them well tested, whilst the controller keeps just the runXYZ functions.

**Review by AlistairEdwinOsborne — APPROVED** [review]
LGTM!

**Review by AlistairEdwinOsborne — DISMISSED** [review]
merges look good!

**Review by AlistairEdwinOsborne — APPROVED** [review]
looks good! nice to keep 809 in there too

**Pull request merged**
