### PR TITLE
Fpla 2379 la docs data migration

### PR DESCRIPTION
**Pull request by nkoranne**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/FPLA-2379

### Change description ###
MigrateCaseController has been updated for data migration with version support

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by lewisbirks — COMMENTED** [review]
You can remove the previous migration, is complete so can be removed

**Comment by lewisbirks** [comment]
Also could you update the tests in the `MigrationControllerTest` (and maybe change the test class name to `MigrateCaseControllerTest`)

**Comment by nkoranne** [comment]
> Also could you update the tests in the `MigrationControllerTest` (and maybe change the test class name to `MigrateCaseControllerTest`)

Basic tests have been added ... logic tests are already covered in UploadDoducmentControllerTest , as migration is using that controller for doing migration

**Comment by nkoranne** [comment]
> Also could you update the tests in the `MigrationControllerTest` (and maybe change the test class name to `MigrateCaseControllerTest`)



> You can remove the previous migration, is complete so can be removed

It's done

**Comment by nkoranne** [comment]
> You can remove the previous migration, is complete so can be removed

Its done

**Pull request closed without merging**
