### PR TITLE
chore: give system update "U" permissions to risks (FPLA-2268)

### PR DESCRIPTION
**Pull request by Jamesnelson117**
**Before creating a pull request make sure that:**

- [x] PR's title includes JIRA ticket number and follow [Conventional Commits](https://www.conventionalcommits.org/) specification
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/FPLA-2268

### Change description ###
DM on production failed to - 
2020-10-06T13:34:29.857 ERROR [main] u.g.hmcts.reform.migration.CaseMigrationProcessor Case 1600945960951828 update failed due to: status 404 reading CoreCaseDataApi#submitEventForCaseWorker(String,String,String,String,String,String,boolean,CaseDataContent)

This was due to 
ccd-data-store-api_1              | 2020-10-07T10:02:27.821 INFO  [http-nio-4452-exec-2] u.g.h.c.d.s.common.CompoundAccessControlService Simple child physicalHarm of risks has data update but no Update ACL

PR updates system user's access to the risks field. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lewisbirks** [comment]
Why would it be trying to update risks? I thought you were just remove the sealed cmo and editing the linked hearing?

**Comment by Jamesnelson117** [comment]
@lewisbirks when ran locally it looks like its insisting on removing two null fields within risks, here is old case data
{"risks": {"neglect": null, "sexualAbuse": "Yes", "physicalHarm": null, "emotionalHarm": "Yes", "sexualAbuseOccurrences": [], "emotionalHarmOccurrences": []},

new
{"risks": {"sexualAbuse": "Yes", "emotionalHarm": "Yes", "sexualAbuseOccurrences": [], "emotionalHarmOccurrences": []},

**Comment by lewisbirks** [comment]
@Jamesnelson117 wonder why we haven't had this issue before then 🤔

**Comment by tomaszpowroznik** [comment]
yeah, this change should not be needed. Looks that data migration could be written in wrong way. 
The method  
public Object migrate(Map<String, Object> data)
is supposed to return event data only and not entire case (only delta)
As we use our own callback and rely on updating case from there then it should return empty map and not entire map of all properties

**Pull request closed without merging**
